const incenseData = [
    {
        id: 1,
        name:  "OUDH INCENSE STICKS",
        regularprice: 199,
        salesprice: 149,
        category: "IncenseSticks",
        unit: "Box",
        stocks: 100,
        mainImage: "https://phool.co/cdn/shop/products/IMG_4690.jpg?v=1603096120" ,
        sideImage1: "https://phool.co/cdn/shop/products/IMG_4690.jpg?v=1603096120",
        sideImage2: "https://phool.co/cdn/shop/products/FRAGRANCECARD-01.jpg?v=1610697119" ,
        description: "Oudh Incense Sticks exude a dominant oriental-woody fragrance accompanied by soft floral notes of vanilla and musk. This rich aroma is born of a unique ecological process in the Aquilaria trees native to Southeast Asia. These trees secrete a protective resinous substance against a rare parasitic fungus, which after extraction, comes to be known as Oudh. Phool Oudh Natural Incense Sticks are an exquisite amalgamation of Oudh extractions, temple flowers, and natural essential oils. With a rich, earthy scent that has the power to soothe and de-stress. Handcrafted by our women flowercyclers with love and care.Phool Natural Incense Sticks pack consists of 40 units. Each stick is 25.4 cm in length with a long burning time of 40-45 minutes. Ideal for your daily meditation and spiritual rituals. Did you know, the Oudh fragrance was a favorite of even the European Royalty, especially King Louis The XIV, who loved it so dearly that he preferred to wash his clothes in it! Bring home the magic of this aristocratic scent with Phool Oudh Natural Incense Sticks.",
    },
    {
        id: 2,
        name:  "LAVEANDER INCENSE STICKS",
        regularprice: 199,
        salesprice: 149,
        category: "IncenseSticks",
        unit: "Box",
        stocks: 100,
        mainImage: "https://phool.co/cdn/shop/products/IMG_5517.jpg?v=1610699394",
        sideImage1: "https://phool.co/cdn/shop/products/FRAGRANCECARD-01.jpg?v=1610697119" ,
        sideImage2: "https://phool.co/cdn/shop/products/IMG_4690.jpg?v=1603096120",
        description: "Lavender Incense Sticks carry a distinctly sweet and mossy scent, accompanied with delicate hints of camphor and a touch of spice. This popular fragrance is harvested from the lavender flower plants that originated in Mediterranean Europe, through a long & tedious process of steam distillation. ",
    },
    {
        id: 3,
        name:  "ORANGE INCENSE STICKS",
        regularprice: 199,
        salesprice: 149,
        category: "IncenseSticks",
        unit: "Box",
        stocks: 100,
        mainImage: "https://phool.co/cdn/shop/products/IMG_5354.jpg?v=1660635311" ,
        sideImage1: "https://phool.co/cdn/shop/products/IMG_4690.jpg?v=1603096120",
        sideImage2:"https://phool.co/cdn/shop/products/FRAGRANCECARD-01.jpg?v=1610697119" ,
        description: "Orange Incense Sticks possess a delightful and uplifting fragrance that is reminiscent of fresh, juicy oranges. The vibrant and citrus fragrance is a byproduct of the essential oil derived from the orange fruit peel, native to Southeast Asia. It is the ideal fragrance for anyone who loves the fruit in any form. Phool Orange Natural Incense Sticks are a fresh amalgamation of sacred temple flowers, pure essential oil and organic orange peels.",
    },
    {
        id: 4,
        name: "TEA-TREE INCENSE STICKS ",
        regularprice: 199,
        salesprice: 149,
        category: "IncenseSticks",
        unit: "Box",
        stocks: 100,
        mainImage: "https://phool.co/cdn/shop/products/IMG_4621.jpg?v=1660635216" ,
        sideImage1: "https://phool.co/cdn/shop/products/IMG_4690.jpg?v=1603096120",
        sideImage2: "https://phool.co/cdn/shop/products/FRAGRANCECARD-01.jpg?v=1610697119" ,
        description: "Tea Tree Incense Sticks have a distinctive and powerful aroma with a hint of camphor. This magical aroma is created by harvesting the leaves of the Tea Tree, scientifically known as Melaleuca alternifolia, and native to Australia. It is one of the most popular naturally occurring substances globally, due to its antimicrobial and antifungal qualities.",
    },
    {
        id: 5,
        name:  "EUCALYPTUS INCENSE STICKS ",
        regularprice: 199,
        salesprice: 149,
        category: "IncenseSticks",
        unit: "Box",
        stocks: 100,
        mainImage: "https://phool.co/cdn/shop/products/IMG_5201.jpg?v=1660635283" ,
        sideImage1: "https://phool.co/cdn/shop/products/IMG_4690.jpg?v=1603096120",
        sideImage2: "https://phool.co/cdn/shop/products/FRAGRANCECARD-01.jpg?v=1610697119" ,
        description: "Eucalyptus Incense Sticks carry a distinctive and robust aroma that is often identified as cool and invigorating. The core contributor to this fragrance is the Eucalyptus essential oil, extracted from the leaves of the Eucalyptus tree, primarily the species known as Eucalyptus globulus, endemic to Australia. The freshness of this aroma is a positive and powerful mood uplifter.",
    }
];

export {incenseData};