const oilData = [
    {
        id: 100,
        name: "PHOOL LEMONGRASS ESSENTIAL OIL (10ML)",
        price: 335,
        description: "It creates a calming environment, relieves exhaustion and rejuvenates the body & mind. Add a few drops of the essential oil in a diffuser to disperse the fragrance.",
        mainImage: "https://phool.co/cdn/shop/files/LemongrassessentialOils1.jpg?v=1702714000" ,       
        fsImage: "https://phool.co/cdn/shop/files/Lemongrass_02.webp?v=1702714000",
        ssImage: "https://phool.co/cdn/shop/files/LemongrassEssentialOil2.jpg?v=1702714000" ,
        inCart : false,
        count : 0,
    },
    {
        id: 101,
        name: "PHOOL FRANKINCENSE ESSENTIAL OIL (10ML)",
        price: 385,
        description: "It creates a calming environment, relieves exhaustion and rejuvenates the body & mind. Add a few drops of the essential oil in a diffuser to disperse the fragrance.",
        mainImage: "https://phool.co/cdn/shop/files/Frankincense-1.jpg?v=1702713826" ,       
        fsImage: "https://phool.co/cdn/shop/files/Frankincense_02.webp?v=1702713826",
        ssImage: "https://phool.co/cdn/shop/files/Frankincense-3.jpg?v=1702713826" ,
        inCart : false,
        count : 0,
    },
    {
        id: 102,
        name: "PHOOL TEA TREE ESSENTIAL OIL (10ML)",
        price: 335,
        description: "It creates a calming environment, relieves exhaustion and rejuvenates the body & mind. Add a few drops of the essential oil in a diffuser to disperse the fragrance.",
        mainImage: "https://phool.co/cdn/shop/files/006A5153copy_2.jpg?v=1702713092" ,       
        fsImage: "https://phool.co/cdn/shop/files/TeaTree_02.webp?v=1702713092",
        ssImage: "https://phool.co/cdn/shop/files/006A5155copy.jpg?v=1702713092" ,
        inCart : false,
        count : 0,
    },
    {
        id: 103,
        name: "PHOOL LAVENDER ESSENTIAL OIL (10ML)",
        price: 395,
        description: "It creates a calming environment, relieves exhaustion and rejuvenates the body & mind. Add a few drops of the essential oil in a diffuser to disperse the fragrance.",
        mainImage: "https://phool.co/cdn/shop/files/Lavender.jpg?v=1702714032" ,       
        fsImage: "https://phool.co/cdn/shop/files/Lavender_02.webp?v=1702714032",
        ssImage: "https://phool.co/cdn/shop/files/lavendercopy.jpg?v=1702714032" ,
        inCart : false,
        count : 0,
    },

    {
        id: 104,
        name: "PHOOL CINNAMON ESSENTIAL OIL (10ML)",
        price: 335,
        description: "It creates a calming environment, relieves exhaustion and rejuvenates the body & mind. Add a few drops of the essential oil in a diffuser to disperse the fragrance.",
        mainImage: "https://phool.co/cdn/shop/files/Cinnamon.jpg?v=1702714213" ,       
        fsImage: "https://phool.co/cdn/shop/files/Cinnamon_02.webp?v=1702714213",
        ssImage: "https://phool.co/cdn/shop/files/cinnamoncopy.jpg?v=1702714213" ,
        inCart : false,
        count : 0,
    },
];
export {oilData};